# Generated by Django 2.0 on 2020-06-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_lend',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='租用单号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='价格')),
                ('date_begin', models.DateField(null=True, verbose_name='起租日期')),
                ('date_end', models.DateField(null=True, verbose_name='讫租日期')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='下单时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='入库人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('shopid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称')),
            ],
            options={
                'verbose_name_plural': '租用下单',
                'verbose_name': '租用下单',
            },
        ),
        migrations.CreateModel(
            name='Device_lend_stockout',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='租用单号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='价格')),
                ('date_begin', models.DateField(null=True, verbose_name='起租日期')),
                ('date_end', models.DateField(null=True, verbose_name='讫租日期')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='出库时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='出库人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('shopid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称')),
            ],
            options={
                'verbose_name_plural': '租用出库',
                'verbose_name': '租用出库',
            },
        ),
        migrations.CreateModel(
            name='Repair_use',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='维修单号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='价格')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='领用时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='领用人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('shopid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称')),
            ],
            options={
                'verbose_name_plural': '维修领用下单',
                'verbose_name': '维修领用下单',
            },
        ),
        migrations.CreateModel(
            name='Repair_use_stockout',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='维修单号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='领用出库时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='出库人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('shopid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称')),
            ],
            options={
                'verbose_name_plural': '维修领用出库',
                'verbose_name': '维修领用出库',
            },
        ),
    ]
