# Generated by Django 2.0 on 2020-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_use',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='下单时间'),
        ),
    ]
