# Generated by Django 2.0 on 2020-07-14 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0010_auto_20200710_1754'),
        ('stockout_manage', '0003_auto_20200701_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_use',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='FRUSelect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | FRU码 | PN码'),
        ),
    ]
