# Generated by Django 2.0 on 2020-07-14 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0004_auto_20200714_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_use',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品类别'),
        ),
    ]
