# Generated by Django 2.0 on 2020-07-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0010_auto_20200710_1754'),
        ('purchase_manage', '0025_auto_20200715_1123'),
        ('stockout_manage', '0008_auto_20200714_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_lend',
            name='price',
        ),
        migrations.RemoveField(
            model_name='device_lend',
            name='shopid',
        ),
        migrations.AddField(
            model_name='device_lend',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所租客户'),
        ),
        migrations.AddField(
            model_name='device_lend',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectDeviceLend', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 商品类别 | FRU码 | PN码 | 数量 | 描述'),
        ),
        migrations.AddField(
            model_name='device_lend',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='device_lend',
            name='author',
            field=models.CharField(default=None, max_length=10, verbose_name='下单人'),
        ),
        migrations.AlterField(
            model_name='device_lend',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
