# Generated by Django 2.0 on 2020-07-15 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0010_auto_20200710_1754'),
        ('params_manage', '0003_device_fru'),
        ('stockout_manage', '0011_remove_device_lend_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_lend_stockout',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='device_lend_stockout',
            name='date_end',
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='FRU',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | FRU码 | PN码'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='PN',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PN码'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='SN',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SN码'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='lendid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockout_manage.Device_lend', verbose_name='租用单号'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='params_manage.Location', verbose_name='库存位置'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='machineModel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='machineSN',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机SN'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='replace',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='替代号'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办')], default=0, verbose_name='出库状态'),
        ),
        migrations.AddField(
            model_name='device_lend_stockout',
            name='useage',
            field=models.IntegerField(default=0, verbose_name='使用年限'),
        ),
        migrations.AlterField(
            model_name='device_lend',
            name='date_begin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='起租日期'),
        ),
        migrations.AlterField(
            model_name='device_lend',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='讫租日期'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='租用出库单'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='price',
            field=models.FloatField(default=1, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品类别'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出库时间'),
        ),
    ]
