# Generated by Django 2.0 on 2020-07-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0012_auto_20200715_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_lend_stockout',
            name='billid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='租用出库单'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
