# Generated by Django 2.0 on 2020-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0013_auto_20200715_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_lend',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办'), (2, '已下单'), (3, '已入库')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办'), (2, '已下单'), (3, '已入库')], default=0, verbose_name='出库状态'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办'), (2, '已下单'), (3, '已入库')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办'), (2, '已下单'), (3, '已入库')], default=0, verbose_name='出库状态'),
        ),
    ]
