# Generated by Django 2.2.14 on 2020-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0021_remove_repair_use_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_lend',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectDeviceLend', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectDeviceRepair', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
    ]
