# Generated by Django 2.2.14 on 2020-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0022_auto_20200901_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_lend',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='下单人'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='出库人'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='下单人'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='出库人'),
        ),
    ]
