# Generated by Django 2.2.14 on 2020-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0023_auto_20200909_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='出库时间'),
        ),
    ]
