# Generated by Django 2.2.14 on 2020-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockout_manage', '0029_auto_20200916_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='update_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='创建日期'),
        ),
    ]
