# Generated by Django 2.2.14 on 2020-10-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0017_auto_20200918_1049'),
        ('stockout_manage', '0032_auto_20200924_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_lend',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所租客户'),
        ),
        migrations.AddField(
            model_name='repair_use',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='device_lend',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所租客户1'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属项目1'),
        ),
    ]
