# Generated by Django 2.2.14 on 2020-10-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0017_auto_20200918_1049'),
        ('stockout_manage', '0033_auto_20201010_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_use_stockout',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属项目1'),
        ),
    ]
