# Generated by Django 2.2.14 on 2020-10-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0017_auto_20200918_1049'),
        ('stockout_manage', '0034_auto_20201012_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_lend_stockout',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所租客户'),
        ),
        migrations.AlterField(
            model_name='device_lend',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所租签约客户'),
        ),
        migrations.AlterField(
            model_name='device_lend_stockout',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所租潜在客户'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='repair_use',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属签约客户'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockout',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属签约客户'),
        ),
    ]
