# Generated by Django 2.2.14 on 2020-09-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('product_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('exp', models.IntegerField(blank=True, default=0, null=True, verbose_name='保质期/年')),
                ('degree', models.FloatField(blank=True, default=0, null=True, verbose_name='度数/%vol')),
                ('volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='容量/ml')),
                ('author_checkin', models.CharField(default=None, max_length=10, verbose_name='入库人')),
                ('checkin_date', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('author_checkout', models.CharField(default=None, max_length=10, verbose_name='出库人')),
                ('checkout_date', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '礼品信息',
                'ordering': ('checkin_date', 'name'),
                'verbose_name_plural': '礼品信息',
            },
        ),
    ]
