# Generated by Django 2.2.14 on 2020-09-22 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='checkin_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='出库时间'),
        ),
    ]
