# Generated by Django 2.2.14 on 2020-09-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0002_auto_20200922_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='author_checkin',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='入库人'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='author_checkout',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='出库人'),
        ),
    ]
