# Generated by Django 2.2.14 on 2020-09-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0003_auto_20200922_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='degree',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='度数(%vol)'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='exp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='保质期(年)'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='容量(ml)'),
        ),
    ]
