# Generated by Django 2.2.14 on 2020-09-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0004_auto_20200922_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='author_user',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='使用人'),
        ),
    ]
