# Generated by Django 2.2.14 on 2020-09-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0005_gifts_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='反面图片'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='正面图片'),
        ),
    ]
