# Generated by Django 2.2.14 on 2020-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0006_auto_20200924_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='quantity_inout',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='出入库'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='库存数量'),
        ),
    ]
