# Generated by Django 2.2.14 on 2020-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0008_gifts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='checkin_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='出库时间'),
        ),
    ]
