# Generated by Django 2.2.14 on 2020-10-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0009_auto_20200924_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gifts',
            options={'ordering': ('name', '-status', '-checkin_date', '-checkout_date'), 'verbose_name': '礼品信息', 'verbose_name_plural': '礼品信息'},
        ),
    ]
