# Generated by Django 2.2.14 on 2020-12-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0013_auto_20201208_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gifts',
            options={'ordering': ('name', '-pub_date'), 'verbose_name': '礼品信息', 'verbose_name_plural': '礼品信息'},
        ),
    ]
