# Generated by Django 2.2.14 on 2020-12-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manage', '0014_auto_20201208_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
    ]
