# Generated by Django 2.0 on 2020-07-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '维护服务类'), (1, '产品销售类')], default=1, verbose_name='合同类型')),
                ('model', models.CharField(blank=True, max_length=30, null=True, verbose_name='型号')),
                ('SN', models.CharField(blank=True, max_length=30, null=True, verbose_name='序列号')),
                ('level', models.CharField(blank=True, max_length=30, null=True, verbose_name='服务级别')),
                ('begindate', models.DateField(default='1900-01-01', verbose_name='服务开始日期')),
                ('enddate', models.DateField(default='1900-01-01', verbose_name='服务结束日期')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务地址')),
                ('deliverydate', models.DateField(default='1900-01-01', verbose_name='交货日期')),
                ('setupdate', models.DateField(default='1900-01-01', verbose_name='安装日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '合同服务内容',
                'verbose_name': '合同服务内容',
            },
        ),
        migrations.CreateModel(
            name='ContractInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='合同金额(¥)')),
                ('paydesc', models.CharField(blank=True, max_length=50, null=True, verbose_name='付款条件')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='税率(%)')),
                ('paydays', models.IntegerField(verbose_name='账期(天)')),
                ('billdate', models.DateField(verbose_name='开票日期')),
                ('paystatus', models.IntegerField(choices=[(0, '未收款'), (1, '已收款')], verbose_name='收款情况')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%m%d', verbose_name='合同文件')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '合同信息',
                'verbose_name': '合同信息',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('base_info', models.CharField(blank=True, max_length=30, null=True, verbose_name='常规资料')),
                ('contract_info', models.CharField(blank=True, max_length=30, null=True, verbose_name='合约资料')),
                ('clue', models.CharField(blank=True, max_length=20, null=True, verbose_name='线索')),
                ('service', models.CharField(blank=True, max_length=20, null=True, verbose_name='维保服务')),
                ('people', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系方式')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系地址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer_type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Customer_type', verbose_name='客户类型')),
            ],
            options={
                'verbose_name_plural': '客户信息',
                'verbose_name': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='CustomersLatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='项目开始日期')),
                ('saler', models.CharField(max_length=30, verbose_name='销售负责人')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='追踪项目')),
                ('rate', models.TextField(blank=True, null=True, verbose_name='追踪进展')),
                ('status', models.IntegerField(choices=[(0, '跟进中'), (1, '已签约')], default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='客户名称')),
            ],
            options={
                'verbose_name_plural': '潜在客户',
                'verbose_name': '潜在客户',
            },
        ),
        migrations.CreateModel(
            name='CustomersSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractid', models.CharField(max_length=30, verbose_name='合同编号')),
                ('pub_date', models.DateField(verbose_name='签约时间')),
                ('type', models.IntegerField(choices=[(0, '维护服务类'), (1, '产品销售类')], default=1, verbose_name='合同类型')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称')),
                ('saler', models.CharField(max_length=30, verbose_name='销售负责人')),
                ('engineer', models.CharField(max_length=30, verbose_name='负责工程师')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='服务内容')),
                ('status', models.IntegerField(choices=[(0, '维护中'), (1, '结束')], default=1, verbose_name='项目状态')),
                ('rptservice', models.FileField(blank=True, null=True, upload_to='files/%m%d', verbose_name='客户服务报告')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='客户名称')),
            ],
            options={
                'verbose_name_plural': '签约客户',
                'verbose_name': '签约客户',
            },
        ),
        migrations.CreateModel(
            name='DeviceStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FRU', models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码')),
                ('PN', models.CharField(blank=True, max_length=15, null=True, verbose_name='PN码')),
                ('machineModel', models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号')),
                ('machineSN', models.CharField(blank=True, max_length=30, null=True, verbose_name='整机SN')),
                ('descs', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
                ('price', models.FloatField(default=0, verbose_name='单价')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('quantityLock', models.IntegerField(default=0, verbose_name='锁定数量')),
                ('quantityLover', models.IntegerField(default=0, verbose_name='最低库存')),
                ('type', models.IntegerField(choices=[(0, '新购'), (1, '回收')], default=1, verbose_name='备件类别')),
                ('source', models.CharField(blank=True, max_length=30, null=True, verbose_name='来源')),
                ('replaces', models.CharField(blank=True, max_length=15, null=True, verbose_name='替代号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='图片')),
                ('location', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Location', verbose_name='库存位置')),
            ],
            options={
                'verbose_name_plural': '库存信息',
                'verbose_name': '库存信息',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类别')),
                ('important', models.CharField(blank=True, max_length=10, null=True, verbose_name='重要性')),
                ('solve', models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否解决')),
                ('desc', models.TextField(verbose_name='场景描述')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='解决方案')),
                ('pub_date', models.DateField(verbose_name='提交日期')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='提交人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '项目需求管理',
                'verbose_name': '项目需求',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='商品代码')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='商品名称')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='商品状态')),
                ('cost', models.FloatField(default=0, verbose_name='采购成本')),
                ('useage', models.IntegerField(default=0, verbose_name='使用年限')),
                ('quantity_good', models.IntegerField(default=0, verbose_name='最佳备货量')),
                ('price', models.FloatField(default=0, verbose_name='标准售价')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_brand', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Base_brand', verbose_name='商品品牌')),
                ('shop_level', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Base_level', verbose_name='商品等级')),
                ('shop_type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Base_type', verbose_name='商品类别')),
            ],
            options={
                'verbose_name_plural': '商品信息',
                'verbose_name': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('adress', models.CharField(blank=True, max_length=30, null=True, verbose_name='地址')),
                ('people', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '供应商信息',
                'verbose_name': '供应商信息',
            },
        ),
        migrations.AddField(
            model_name='devicestores',
            name='shop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='devicestores',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Suppliers', verbose_name='首选供应商'),
        ),
        migrations.AddField(
            model_name='contractinfo',
            name='contractid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='合同编号'),
        ),
        migrations.AddField(
            model_name='contractcontent',
            name='contractid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='合同编号'),
        ),
    ]
