# Generated by Django 2.0 on 2020-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestores',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
    ]
