# Generated by Django 2.0 on 2020-07-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0002_auto_20200702_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestores',
            name='ifmachine',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否整机备件'),
        ),
    ]
