# Generated by Django 2.0 on 2020-07-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0003_devicestores_ifmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestores',
            name='ifmachine',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否整机备件'),
        ),
    ]
