# Generated by Django 2.0 on 2020-07-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0006_auto_20200708_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestores',
            name='machineModel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Device_kind', verbose_name='整机型号'),
        ),
    ]
