# Generated by Django 2.0 on 2020-07-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0002_auto_20200708_1740'),
        ('baseinfo_manage', '0007_auto_20200708_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestores',
            name='machineModels',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Device_kind', verbose_name='整机型号'),
        ),
        migrations.AlterField(
            model_name='devicestores',
            name='machineModel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号'),
        ),
    ]
