# Generated by Django 2.0 on 2020-07-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0009_devicestores_frus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestores',
            name='suppliers',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Suppliers', verbose_name='首选供应商'),
        ),
    ]
