# Generated by Django 2.0 on 2020-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0010_auto_20200710_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestores',
            options={'ordering': ('machineModels', 'shop'), 'verbose_name': '商品明细', 'verbose_name_plural': '商品明细'},
        ),
        migrations.AddField(
            model_name='devicestores',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='备件二维码'),
        ),
    ]
