# Generated by Django 2.2.14 on 2020-08-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0011_auto_20200717_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestores',
            options={'ordering': ('machineModels', 'shop'), 'verbose_name': '备件明细', 'verbose_name_plural': '备件明细'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '备件信息', 'verbose_name_plural': '备件信息'},
        ),
        migrations.AlterField(
            model_name='devicestores',
            name='FRUS',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Device_FRU', verbose_name='FRU码 [备件描述]'),
        ),
        migrations.AlterField(
            model_name='devicestores',
            name='descs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
        migrations.AlterField(
            model_name='devicestores',
            name='shop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件类别'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='备件名称'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_brand',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Base_brand', verbose_name='备件品牌'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_level',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Base_level', verbose_name='备件等级'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Base_type', verbose_name='备件类别'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='备件状态'),
        ),
    ]
