# Generated by Django 2.2.14 on 2020-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0013_auto_20200901_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerslatent',
            name='status',
            field=models.IntegerField(choices=[(0, '跟进中'), (1, '已签约')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='customerssign',
            name='status',
            field=models.IntegerField(choices=[(0, '维护中'), (1, '结束')], default=0, verbose_name='项目状态'),
        ),
    ]
