# Generated by Django 2.2.14 on 2020-09-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0016_auto_20200918_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectorderdetail',
            options={'ordering': ['device'], 'verbose_name': '备件申请信息', 'verbose_name_plural': '备件申请信息'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('shop_type',), 'verbose_name': '备件类别', 'verbose_name_plural': '备件类别'},
        ),
    ]
