# Generated by Django 2.2.14 on 2020-12-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0017_auto_20200918_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Device_type', verbose_name='备件类型'),
        ),
    ]
