# Generated by Django 2.2.14 on 2020-12-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0022_auto_20201202_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestores',
            name='machineModel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='devicestores',
            name='machineModels',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='params_manage.Device_kind', verbose_name='型号'),
        ),
    ]
