# Generated by Django 2.2.14 on 2020-09-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0035_auto_20200909_1605'),
        ('baseinfo_manage', '0014_auto_20200909_1122'),
        ('sale_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_out',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='销售客户'),
        ),
        migrations.AddField(
            model_name='sales_out',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectDeviceSales', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
        migrations.AddField(
            model_name='sales_out',
            name='status',
            field=models.IntegerField(choices=[(0, '待提交'), (1, '采购中'), (2, '待下单'), (3, '已下单'), (4, '待入库'), (5, '已入库'), (6, '待出库'), (7, '已出库'), (8, '部分入库'), (9, '部分出库')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='sales_out',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='下单人'),
        ),
        migrations.AlterField(
            model_name='sales_out',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
