# Generated by Django 2.2.14 on 2020-09-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0003_auto_20200911_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_out',
            name='machineSelects',
        ),
    ]
