# Generated by Django 2.2.14 on 2020-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0035_auto_20200909_1605'),
        ('sale_manage', '0004_remove_sales_out_machineselects'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_out',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectDeviceSales', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
    ]
