# Generated by Django 2.2.14 on 2020-09-11 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0006_auto_20200813_1625'),
        ('baseinfo_manage', '0014_auto_20200909_1122'),
        ('sale_manage', '0005_sales_out_machineselects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_out_stockout',
            options={'verbose_name': '销售出库', 'verbose_name_plural': '销售出库'},
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='FRU',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='PN',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PN码'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='SN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SN码'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='billid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='销售出库单'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='ifsure',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否已确认'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='lendid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sale_manage.Sales_out', verbose_name='销售单'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='params_manage.Location', verbose_name='库存位置'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='machineModel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='machineSN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='整机SN'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='replace',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='替代号'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='status',
            field=models.IntegerField(choices=[(0, '待提交'), (1, '采购中'), (2, '待下单'), (3, '已下单'), (4, '待入库'), (5, '已入库'), (6, '待出库'), (7, '已出库'), (8, '部分入库'), (9, '部分出库')], default=6, verbose_name='出库状态'),
        ),
        migrations.AddField(
            model_name='sales_out_stockout',
            name='useage',
            field=models.IntegerField(default=0, verbose_name='使用年限'),
        ),
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='出库人'),
        ),
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='price',
            field=models.FloatField(default=1, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件类别'),
        ),
    ]
