# Generated by Django 2.2.14 on 2020-09-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0006_auto_20200911_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_out_stockout',
            old_name='lendid',
            new_name='saleid',
        ),
    ]
