# Generated by Django 2.2.14 on 2020-09-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0007_auto_20200911_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='销售客户'),
        ),
    ]
