# Generated by Django 2.2.14 on 2020-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0008_auto_20200914_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_out_stockout',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='出库时间'),
        ),
    ]
