# Generated by Django 2.2.14 on 2020-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_manage', '0009_auto_20200915_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_out',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='下单时间'),
        ),
    ]
