# Generated by Django 2.0 on 2020-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='useage',
            field=models.IntegerField(default=0, verbose_name='使用年限'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='author',
            field=models.CharField(default=None, max_length=10, verbose_name='入库人'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='入库时间'),
        ),
    ]
