# Generated by Django 2.0 on 2020-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='machineModel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号'),
        ),
        migrations.AddField(
            model_name='purchase_order_detail',
            name='machineSN',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机SN'),
        ),
        migrations.AddField(
            model_name='purchase_stockin_detail',
            name='machineModel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号'),
        ),
        migrations.AddField(
            model_name='purchase_stockin_detail',
            name='machineSN',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机SN'),
        ),
    ]
