# Generated by Django 2.0 on 2020-07-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0004_auto_20200706_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='ifmachine',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否整机备件'),
        ),
    ]
