# Generated by Django 2.0 on 2020-07-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0004_auto_20200706_1043'),
        ('purchase_manage', '0006_auto_20200706_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, related_name='machineSelect', to='baseinfo_manage.DeviceStores', verbose_name='整机型号 / 商品名称 / FRU码 / PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 / 商品名称 / FRU码 / PN码'),
        ),
    ]
