# Generated by Django 2.0 on 2020-07-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0007_auto_20200706_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase_stockin_detail',
            options={'ordering': ['purchase_id', 'bill_id', 'shopid'], 'verbose_name': '采购入库', 'verbose_name_plural': '采购入库'},
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 / 商品名称 / FRU码 / PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='采购入库申请单号'),
        ),
    ]
