# Generated by Django 2.0 on 2020-07-07 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0008_auto_20200707_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='arrive_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='最晚到货日期'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='purchasedesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购说明'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品类别'),
        ),
    ]
