# Generated by Django 2.0 on 2020-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0010_auto_20200707_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='purchasedesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购说明'),
        ),
    ]
