# Generated by Django 2.0 on 2020-07-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0011_auto_20200707_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='商品描述'),
        ),
    ]
