# Generated by Django 2.0 on 2020-07-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0006_auto_20200708_1615'),
        ('purchase_manage', '0013_auto_20200708_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品描述')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='申请数量')),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 / 商品名称 / FRU码 / PN码')),
            ],
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrderDetail', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 / 商品名称 / FRU码 / PN码 / 描述 / 数量'),
        ),
    ]
