# Generated by Django 2.0 on 2020-07-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0014_auto_20200708_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectorderdetail',
            options={'verbose_name': '备件选择明细', 'verbose_name_plural': '备件选择明细'},
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办')], default=0, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrderDetail', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 / 商品名称 / FRU码 / PN码 / 数量 / 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='采购数量'),
        ),
        migrations.AlterField(
            model_name='selectorderdetail',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 / 商品类别 / FRU码 / PN码'),
        ),
    ]
