# Generated by Django 2.0 on 2020-07-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0015_auto_20200709_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
