# Generated by Django 2.0 on 2020-07-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0016_auto_20200709_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrderDetail', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 / 商品名称 / FRU码 / PN码 / 数量 / 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrder', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 / 商品名称 / FRU码 / PN码 / 数量 / 描述'),
        ),
    ]
