# Generated by Django 2.0 on 2020-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0017_auto_20200709_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办')], default=0, verbose_name='下单状态'),
        ),
    ]
