# Generated by Django 2.0 on 2020-07-10 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0009_devicestores_frus'),
        ('purchase_manage', '0018_purchase_order_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='suppliersid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Suppliers', verbose_name='供应商名称'),
        ),
    ]
