# Generated by Django 2.0 on 2020-07-10 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0009_devicestores_frus'),
        ('purchase_manage', '0019_purchase_order_detail_suppliersid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='所属项目'),
        ),
    ]
