# Generated by Django 2.0 on 2020-07-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0009_devicestores_frus'),
        ('purchase_manage', '0020_purchase_order_customerssignid'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectorderdetail',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品类别'),
        ),
    ]
