# Generated by Django 2.0 on 2020-07-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0021_selectorderdetail_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, related_name='machineSelectOrder', to='baseinfo_manage.DeviceStores', verbose_name='商品类别 / 整机型号 / FRU码 / PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrder', to='purchase_manage.SelectOrderDetail', verbose_name='商品类别 / 整机型号 / FRU码 / PN码 / 数量 / 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='purchase_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='params_manage.Purchase_type', verbose_name='采购类型'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='商品类别 / 整机型号 / FRU码 / PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, related_name='machineSelect', to='baseinfo_manage.DeviceStores', verbose_name='商品类别 / 整机型号 / FRU码 / PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrderDetail', to='purchase_manage.SelectOrderDetail', verbose_name='商品类别 / 整机型号 / FRU码 / PN码 / 数量 / 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='FRUSelect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='商品类别 / 整机型号 / FRU码 / PN码'),
        ),
        migrations.AlterField(
            model_name='selectorderdetail',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='商品类别 / 整机型号 / FRU码 / PN码'),
        ),
    ]
