# Generated by Django 2.0 on 2020-07-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0022_auto_20200710_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, related_name='machineSelectOrder', to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | FRU码 | PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrder', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 商品类别 | FRU码 | PN码 | 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | FRU码 | PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, related_name='machineSelect', to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | 整 FRU码 | PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrderDetail', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 商品类别 | FRU码 | PN码 | 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='FRUSelect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 / 商品类别 /  FRU码 / PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='params_manage.Location', verbose_name='库存位置'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='useage',
            field=models.IntegerField(default=0, verbose_name='使用年限'),
        ),
        migrations.AlterField(
            model_name='selectorderdetail',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | FRU码 | PN码'),
        ),
    ]
