# Generated by Django 2.0 on 2020-07-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0023_auto_20200713_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_stockin_detail',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办')], default=0, verbose_name='入库状态'),
        ),
    ]
