# Generated by Django 2.2.14 on 2020-08-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0029_auto_20200729_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, related_name='machineSelectOrder', to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrder', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件类别'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, null=True, related_name='machineSelect', to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='SelectOrderDetail', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件名称'),
        ),
        migrations.AlterField(
            model_name='purchase_return',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件名称'),
        ),
        migrations.AlterField(
            model_name='purchase_returnout',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件名称'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件名称'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='FRUSelect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件名称'),
        ),
        migrations.AlterField(
            model_name='selectorderdetail',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
        migrations.AlterField(
            model_name='selectorderdetail',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量'),
        ),
        migrations.AlterField(
            model_name='selectorderdetail',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件类别'),
        ),
    ]
