# Generated by Django 2.2.14 on 2020-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0030_auto_20200813_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase_stockin_detail',
            options={'ordering': ['status', 'purchase_id', '-bill_id', 'shopid'], 'verbose_name': '采购入库', 'verbose_name_plural': '采购入库'},
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='SN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SN码'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='machineSN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='整机SN'),
        ),
    ]
