# Generated by Django 2.2.14 on 2020-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0031_auto_20200819_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, related_name='machineSelectOrder', to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectOrder', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelect',
            field=models.ManyToManyField(blank=True, related_name='machineSelect', to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectOrderDetail', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
    ]
