# Generated by Django 2.2.14 on 2020-09-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0033_auto_20200904_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='采购单流程追踪'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='入库人'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='采购单流程追踪'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='shopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件类别'),
        ),
    ]
