# Generated by Django 2.2.14 on 2020-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0034_auto_20200909_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='下单人'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='下单人'),
        ),
    ]
