# Generated by Django 2.2.14 on 2020-09-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0037_auto_20200914_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectorderdetail',
            options={'ordering': ['device'], 'verbose_name': '备件选择明细', 'verbose_name_plural': '备件选择明细'},
        ),
    ]
