# Generated by Django 2.2.14 on 2020-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0038_auto_20200915_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='update_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='update_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='purchase_stockin_detail',
            name='update_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
    ]
