# Generated by Django 2.2.14 on 2020-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0027_auto_20200918_1021'),
        ('sale_manage', '0014_auto_20200918_1021'),
        ('stockout_manage', '0031_auto_20200918_1021'),
        ('purchase_manage', '0039_auto_20200916_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectOrder', to='baseinfo_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='SelectOrderDetail', to='baseinfo_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量 | 数量 | 描述'),
        ),
        migrations.DeleteModel(
            name='SelectOrderDetail',
        ),
    ]
