# Generated by Django 2.2.14 on 2020-10-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0017_auto_20200918_1049'),
        ('purchase_manage', '0042_auto_20201010_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_detail',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='purchase_stockin_detail',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='customersSignid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.CustomersSign', verbose_name='签约项目'),
        ),
    ]
