# Generated by Django 2.0 on 2020-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品品牌')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '商品品牌',
                'verbose_name': '商品品牌',
            },
        ),
        migrations.CreateModel(
            name='Base_brand_child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品子品牌')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '商品子品牌',
                'verbose_name': '商品子品牌',
            },
        ),
        migrations.CreateModel(
            name='Base_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品等级')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '商品等级',
                'verbose_name': '商品等级',
            },
        ),
        migrations.CreateModel(
            name='Base_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品类别')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '商品类别',
                'verbose_name': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='Customer_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10, verbose_name='客户ID')),
                ('address_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='地址类型')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户名称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('people', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系方式')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '客户地址信息',
                'verbose_name': '客户地址信息',
            },
        ),
        migrations.CreateModel(
            name='Customer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='客户类型')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '客户类型',
                'verbose_name': '客户类型',
            },
        ),
        migrations.CreateModel(
            name='Device_kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '备件类型',
                'verbose_name': '备件类型',
            },
        ),
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='备件类别')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '备件类别',
                'verbose_name': '备件类别',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='库位代码')),
                ('name', models.CharField(max_length=10, verbose_name='库存位置')),
                ('level1', models.CharField(blank=True, max_length=20, null=True, verbose_name='库位一级')),
                ('level2', models.CharField(blank=True, max_length=10, null=True, verbose_name='库位二级')),
                ('level3', models.CharField(blank=True, max_length=10, null=True, verbose_name='库位三级')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '库位',
                'verbose_name': '库位',
            },
        ),
        migrations.CreateModel(
            name='Purchase_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='采购类型')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '采购类型',
                'verbose_name': '采购类型',
            },
        ),
    ]
