# Generated by Django 2.0 on 2020-07-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device_kind',
            options={'verbose_name': '整机类型', 'verbose_name_plural': '整机类型'},
        ),
    ]
