# Generated by Django 2.0 on 2020-07-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0003_device_fru'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_fru',
            name='desc',
            field=models.CharField(default='', max_length=10, verbose_name='描述信息'),
        ),
    ]
