# Generated by Django 2.2.14 on 2020-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0005_auto_20200717_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_brand',
            options={'verbose_name': '备件品牌', 'verbose_name_plural': '备件品牌'},
        ),
        migrations.AlterModelOptions(
            name='base_brand_child',
            options={'verbose_name': '备件子品牌', 'verbose_name_plural': '备件子品牌'},
        ),
        migrations.AlterModelOptions(
            name='base_level',
            options={'verbose_name': '备件等级', 'verbose_name_plural': '备件等级'},
        ),
        migrations.AlterModelOptions(
            name='base_type',
            options={'verbose_name': '备件类别', 'verbose_name_plural': '备件类别'},
        ),
        migrations.AlterField(
            model_name='base_brand',
            name='name',
            field=models.CharField(max_length=20, verbose_name='备件品牌'),
        ),
        migrations.AlterField(
            model_name='base_brand_child',
            name='name',
            field=models.CharField(max_length=20, verbose_name='备件子品牌'),
        ),
        migrations.AlterField(
            model_name='base_level',
            name='name',
            field=models.CharField(max_length=20, verbose_name='备件等级'),
        ),
        migrations.AlterField(
            model_name='base_type',
            name='name',
            field=models.CharField(max_length=20, verbose_name='备件类别'),
        ),
    ]
