# Generated by Django 2.2.14 on 2020-09-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0006_auto_20200813_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device_fru',
            options={'ordering': ('name',), 'verbose_name': 'FRU信息', 'verbose_name_plural': 'FRU信息'},
        ),
    ]
