# Generated by Django 2.2.14 on 2020-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0007_auto_20200915_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device_type',
            options={'verbose_name': '备件类型', 'verbose_name_plural': '备件类型'},
        ),
        migrations.AlterField(
            model_name='device_type',
            name='name',
            field=models.CharField(max_length=20, verbose_name='备件类型'),
        ),
    ]
