# Generated by Django 2.2.14 on 2020-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0008_auto_20201202_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device_type',
            options={'verbose_name': '设备类型', 'verbose_name_plural': '设备类型'},
        ),
        migrations.AlterField(
            model_name='device_type',
            name='name',
            field=models.CharField(max_length=20, verbose_name='设备类型'),
        ),
    ]
