# Generated by Django 2.0 on 2020-06-30 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.IntegerField(choices=[(0, '采购入库'), (1, '采购退货出库'), (2, '销售入库'), (3, '销售退货入库'), (4, '租用出库'), (5, '回收入库'), (6, '维修领用出库'), (7, '维修返回入库'), (8, '调拨出库'), (9, '调拨入库')], default=0, verbose_name='单据类型')),
                ('bill_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='入库单号')),
                ('shop', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品名称')),
                ('FRU', models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码')),
                ('SN', models.CharField(blank=True, max_length=15, null=True, verbose_name='SN码')),
                ('PN', models.CharField(blank=True, max_length=15, null=True, verbose_name='PN码')),
                ('machineModel', models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号')),
                ('machineSN', models.CharField(blank=True, max_length=30, null=True, verbose_name='整机SN')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
                ('source', models.CharField(blank=True, max_length=30, null=True, verbose_name='来源')),
                ('replace', models.CharField(blank=True, max_length=15, null=True, verbose_name='替代号')),
                ('useage', models.IntegerField(verbose_name='使用年限')),
                ('price', models.FloatField(verbose_name='单价')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='图片')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateField(null=True, verbose_name='入库时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='入库人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params_manage.Location', verbose_name='库存位置')),
            ],
            options={
                'verbose_name': '出入库明细',
                'verbose_name_plural': '出入库明细',
            },
        ),
    ]
