# Generated by Django 2.0 on 2020-06-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0001_initial'),
        ('report_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='FRU码 / PN码 / 整机型号'),
        ),
    ]
