# Generated by Django 2.0 on 2020-07-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0010_auto_20200710_1754'),
        ('report_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='shopid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | FRU码 | PN码'),
        ),
    ]
