# Generated by Django 2.0 on 2020-07-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0002_auto_20200713_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_detail',
            options={'verbose_name': '出入库信息', 'verbose_name_plural': '出入库信息'},
        ),
        migrations.AddField(
            model_name='stock_detail',
            name='stock_type',
            field=models.IntegerField(choices=[(0, '入库'), (1, '出库')], default=0, verbose_name='出入库类型'),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='author',
            field=models.CharField(default=None, max_length=10, verbose_name='出入库人'),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='出入库时间'),
        ),
    ]
