# Generated by Django 2.2.14 on 2020-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0005_auto_20200813_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplaceIBM_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineSN', models.CharField(blank=True, max_length=30, null=True, verbose_name='机型-型号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='备件名称')),
                ('ccin', models.CharField(blank=True, max_length=30, null=True, verbose_name='CCIN号')),
                ('fc', models.CharField(blank=True, max_length=30, null=True, verbose_name='FC号')),
                ('partNo', models.CharField(blank=True, max_length=30, null=True, verbose_name='备件号')),
                ('replace', models.CharField(blank=True, max_length=300, null=True, verbose_name='替代号(多个以逗号分隔)')),
                ('descs', models.CharField(blank=True, max_length=30, null=True, verbose_name='备件描述')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': 'IBM替代号查询',
                'verbose_name': 'IBM替代号查询',
            },
        ),
    ]
