# Generated by Django 2.2.14 on 2020-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0006_replaceibm_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='bill_type',
            field=models.IntegerField(choices=[(0, '采购入库'), (1, '采购退货出库'), (2, '销售出库'), (3, '销售退货入库'), (4, '租用出库'), (5, '回收入库'), (6, '维修领用出库'), (7, '维修返回入库'), (8, '调拨出库'), (9, '调拨入库'), (10, '历史库存入库')], default=0, verbose_name='单据类型'),
        ),
    ]
