# Generated by Django 2.2.14 on 2020-09-14 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0007_auto_20200914_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='出入库时间'),
        ),
    ]
