# Generated by Django 2.2.14 on 2020-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0008_auto_20200914_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='update_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='创建日期'),
        ),
    ]
