# Generated by Django 2.2.14 on 2020-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0009_auto_20200916_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowstatus1', models.CharField(blank=True, max_length=20, null=True, verbose_name='流程状态1')),
                ('name1', models.CharField(blank=True, max_length=30, null=True, verbose_name='申请单号')),
                ('FRU1', models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码')),
                ('author1', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time1', models.DateTimeField(default=None, null=True, verbose_name='提交时间')),
                ('flowstatus2', models.CharField(blank=True, max_length=20, null=True, verbose_name='流程状态2')),
                ('name2', models.CharField(blank=True, max_length=30, null=True, verbose_name='申请单号')),
                ('FRU2', models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码')),
                ('author2', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time2', models.DateTimeField(default=None, null=True, verbose_name='提交时间')),
                ('flowstatus3', models.CharField(blank=True, max_length=20, null=True, verbose_name='流程状态3')),
                ('name3', models.CharField(blank=True, max_length=30, null=True, verbose_name='申请单号')),
                ('FRU3', models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码')),
                ('author3', models.CharField(default=None, max_length=10, verbose_name='操作人')),
                ('update_time3', models.DateTimeField(default=None, null=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name_plural': '单据流程信息查询',
                'verbose_name': '单据流程信息查询',
            },
        ),
    ]
