# Generated by Django 2.2.14 on 2020-09-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0010_workflow_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_query',
            name='author1',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='workflow_query',
            name='author2',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='workflow_query',
            name='author3',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='操作人'),
        ),
    ]
