# Generated by Django 2.2.14 on 2020-09-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0011_auto_20200918_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_query',
            name='FRU2',
        ),
        migrations.RemoveField(
            model_name='workflow_query',
            name='FRU3',
        ),
    ]
