# Generated by Django 2.2.14 on 2020-09-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0012_auto_20200918_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow_query',
            options={'verbose_name': '单据流程信息', 'verbose_name_plural': '单据流程信息'},
        ),
        migrations.RenameField(
            model_name='workflow_query',
            old_name='FRU1',
            new_name='FRU',
        ),
        migrations.AlterField(
            model_name='workflow_query',
            name='name1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='单据号'),
        ),
        migrations.AlterField(
            model_name='workflow_query',
            name='name2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='单据号'),
        ),
        migrations.AlterField(
            model_name='workflow_query',
            name='name3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='单据号'),
        ),
    ]
