# Generated by Django 2.2.14 on 2020-09-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0017_auto_20200918_1049'),
        ('report_manage', '0013_auto_20200918_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_query',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量'),
        ),
    ]
