# Generated by Django 2.2.14 on 2020-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0014_workflow_query_fruselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_query',
            name='pid',
            field=models.IntegerField(default='0', verbose_name='申请单号ID'),
        ),
    ]
