# Generated by Django 2.2.14 on 2020-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0015_workflow_query_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_query',
            name='pid',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='申请单号ID'),
        ),
    ]
