# Generated by Django 2.2.14 on 2020-10-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0017_auto_20200918_1049'),
        ('report_manage', '0017_auto_20200922_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='客户'),
        ),
    ]
