# Generated by Django 2.2.14 on 2020-10-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_manage', '0018_stock_detail_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_detail',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='项目客户'),
        ),
    ]
