# Generated by Django 2.0 on 2020-06-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_return',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='回收单号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='回收价格')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='回收时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='回收人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('shopid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称')),
            ],
            options={
                'verbose_name_plural': '回收下单',
                'verbose_name': '回收下单',
            },
        ),
        migrations.CreateModel(
            name='Device_return_stockin',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='回收入库单')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='回收入库时间')),
                ('author', models.CharField(default=None, max_length=10, verbose_name='入库人')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('shopid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='商品名称')),
            ],
            options={
                'verbose_name_plural': '回收入库',
                'verbose_name': '回收入库',
            },
        ),
    ]
