# Generated by Django 2.0 on 2020-07-20 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0003_remove_repair_use_stockin_shopid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return_stockin',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='回收入库时间'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办'), (2, '已下单'), (3, '已入库')], default=0, verbose_name='入库状态'),
        ),
    ]
