# Generated by Django 2.0 on 2020-07-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_manage', '0026_auto_20200720_1016'),
        ('baseinfo_manage', '0011_auto_20200717_1053'),
        ('stockin_manage', '0004_auto_20200720_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_return',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='device_return',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='Selectreturn', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 商品类别 | FRU码 | PN码 | 数量 | 描述'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='Selectreturnstockin', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 商品类别 | FRU码 | PN码 | 数量 | 描述'),
        ),
    ]
