# Generated by Django 2.0 on 2020-07-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo_manage', '0011_auto_20200717_1053'),
        ('stockin_manage', '0005_auto_20200720_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_return',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Customers', verbose_name='客户'),
        ),
    ]
