# Generated by Django 2.0 on 2020-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0006_device_return_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return',
            name='price',
            field=models.FloatField(default=0, verbose_name='回收价格'),
        ),
        migrations.AlterField(
            model_name='device_return',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='device_return',
            name='remark',
            field=models.CharField(default=None, max_length=100, verbose_name='备注'),
        ),
    ]
