# Generated by Django 2.0 on 2020-07-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0007_auto_20200720_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
