# Generated by Django 2.0 on 2020-07-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0009_device_return_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_return',
            name='shopid',
        ),
    ]
