# Generated by Django 2.0 on 2020-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0010_remove_device_return_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_return_stockin',
            name='status',
            field=models.IntegerField(choices=[(0, '待办'), (1, '已办'), (2, '已下单'), (3, '已入库')], default=0, verbose_name='回收状态'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
