# Generated by Django 2.0 on 2020-07-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params_manage', '0005_auto_20200717_1157'),
        ('baseinfo_manage', '0011_auto_20200717_1053'),
        ('stockin_manage', '0011_auto_20200720_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_return_stockin',
            name='machineSelects',
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='FRU',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='FRU码'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 商品类别 | FRU码 | PN码'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='PN',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PN码'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='SN',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SN码'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='billid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='采购入库单号'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%m%d', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='params_manage.Location', verbose_name='库存位置'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='machineModel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机型号'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='machineSN',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='整机SN'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='replace',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='替代号'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='returnid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockin_manage.Device_return', verbose_name='回收单号'),
        ),
        migrations.AddField(
            model_name='device_return_stockin',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
