# Generated by Django 2.2.14 on 2020-08-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0014_auto_20200729_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, null=True, related_name='Selectreturn', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量| 数量 | 描述'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='FRUSelect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='shopid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.Shop', verbose_name='备件名称'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='FRUSelect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo_manage.DeviceStores', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备件描述'),
        ),
    ]
