# Generated by Django 2.2.14 on 2020-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0015_auto_20200813_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return_stockin',
            name='SN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SN码'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='machineSN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='整机SN'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='SN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SN码'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='machineSN',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='整机SN'),
        ),
    ]
