# Generated by Django 2.2.14 on 2020-08-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0016_auto_20200819_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return_stockin',
            name='billid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='回收入库单号'),
        ),
    ]
