# Generated by Django 2.2.14 on 2020-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0017_auto_20200820_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return',
            name='machineSelects',
            field=models.ManyToManyField(blank=True, related_name='Selectreturn', to='purchase_manage.SelectOrderDetail', verbose_name='整机型号 | 备件类别 | FRU码 | PN码 | 库存量| 数量 | 描述'),
        ),
    ]
