# Generated by Django 2.2.14 on 2020-09-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0018_auto_20200901_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return',
            name='author',
            field=models.CharField(default=None, max_length=10, verbose_name='下单人'),
        ),
    ]
