# Generated by Django 2.2.14 on 2020-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0019_auto_20200904_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='下单人'),
        ),
        migrations.AlterField(
            model_name='device_return_stockin',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='入库人'),
        ),
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='author',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='入库人'),
        ),
    ]
