# Generated by Django 2.2.14 on 2020-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0024_auto_20200916_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_return_stockin',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='入库时间'),
        ),
    ]
