# Generated by Django 2.2.14 on 2020-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin_manage', '0025_auto_20200916_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_use_stockin',
            name='update_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='创建日期'),
        ),
    ]
